### ISSUE TITLE
Update with Gutenberg Gaussholder fixes

### ISSUE THREAD

**Issue by joehoyle** [humanmade/platform-media#9]
Blocked on:

- [x] https://github.com/humanmade/Gaussholder/pull/37
- [x] https://github.com/humanmade/Gaussholder/pull/38

**Comment by roborourke** [comment]
@joehoyle good to go here

**Comment by roborourke** [comment]
Ok set up CI for Gaussholder so build script is run and tags are automatically pushed when the `Version: x.x.x` string in the main plugin file is changed.

**Comment by joehoyle** [comment]
`r/madlads`

**Comment by roborourke** [comment]
Fixed in #13
